//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dazzprise1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class combo
    {
        public int id { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_catalogo { get; set; }
        public string estado { get; set; }
        public Nullable<int> id_producto { get; set; }
    
        public virtual catalogo catalogo { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual producto producto { get; set; }
    }
}
